apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/bucket23/nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: image.tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/bucket23/nginx:1.21
          ports:
            - containerPort: 80
