apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: dev-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Arpit-Sharma-as/nginx-argo-app
    targetRevision: HEAD
    path: apps/nginx-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
